import scipy.io as sio

# ---------------------
#  Global Parameters
# ---------------------
Nt = 64  # the number of antennas
P = 1   # the normalized transmit power



# load the saved .mat files generated by Matlab.
def mat_load(path):
    print('loading data...')
    # load the perfect csi
    h = sio.loadmat(path + '/pcsi.mat')['pcsi']
    # load the estimated csi
    h_est = sio.loadmat(path + '/ecsi.mat')['ecsi']
    print('loading complete')
    print('The shape of CSI is: ', h_est.shape)
    return h, h_est
